---
- name: Export path cargo
  lineinfile:
    path: $HOME/.zshrc
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - { regexp: '^#EXPORT_CARGO', line: 'export PATH=$HOME/.cargo/bin:$HOME/.local/bin:$PATH'}
